[package]
name = "node-runtime"
version = "0.0.1"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0.0"
log = "0.4"
byteorder = "1.2"
kvdb = "0.1"
rand = "0.6"
rand_xorshift = "0.1"
ethash = "0.3"
ethereum-bigint = "0.2"

primitives = { path = "../../core/primitives" }
storage = { path = "../../core/storage" }
wasm = { path = "../../core/wasm" }
configs = { path = "../configs" }
chain = { path = "../../core/chain" }

[features]
test-utils = []

[dev-dependencies]
tempdir = "0.3"
bencher = "0.1.5"
ethereum-rlp = "0.2"
ethereum-block = "0.3"
ethereum-hexutil = "0.2"

[[bench]]
name = "bench"
harness = false
